# Generated by Django 2.2.2 on 2020-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phonenumber', models.CharField(max_length=122)),
                ('style', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
